# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dPRaXFw4Cw4w_qxDOvCkAJlf2a2-XI2i
"""

import streamlit as st
import joblib
import pandas as pd
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk

nltk.download('stopwords')
nltk.download('punkt')

# Load the saved model, vectorizer, and emotion mapping
@st.cache_resource # Cache the resource to avoid reloading on each rerun
def load_resources():
    model = joblib.load('lr_model_bow.pkl')
    vectorizer = joblib.load('bow_vectorizer.pkl')
    emotion_map = joblib.load('emotion_mapping.pkl')
    # Invert the emotion_map to get emotion names from numbers for display
    reverse_emotion_map = {v: k for k, v in emotion_map.items()}
    return model, vectorizer, reverse_emotion_map

model, bow_vectorizer, reverse_emotion_map = load_resources()

# Preprocessing functions (copied from your notebook)
def remove_punc(txt):
    txt = str(txt)
    return txt.translate(str.maketrans('','',string.punctuation))

def remove_emj(txt):
    new= ""
    for i in txt:
        if i.isascii():
            new+=i
    return new

def remove_no(txt):
    new= ""
    for i in txt:
        if i.isdigit(): # Corrected: Original function had a bug, check for digit
            pass # If it's a digit, we want to remove it, so do nothing
        else:
            new+=i
    return new

stop_words = set(stopwords.words('english'))
def remove_st_words(text):
    words = text.split()
    clean_text= []
    for i in words:
        if i not in stop_words:
            clean_text.append(i)
    return ' '.join(clean_text)

def preprocess_text(text):
    text = text.lower()
    text = remove_punc(text)
    text = remove_emj(text)
    text = remove_no(text)
    text = remove_st_words(text)
    return text

# Streamlit app layout
st.title("Emotion Prediction App")
st.write("Enter a sentence to predict its emotion.")

user_input = st.text_area("Your Sentence:", "I feel very happy today!")

if st.button("Predict Emotion"):
    if user_input:
        # Preprocess the input text
        processed_input = preprocess_text(user_input)

        # Transform the preprocessed text using the loaded vectorizer
        input_vectorized = bow_vectorizer.transform([processed_input])

        # Make prediction
        prediction_numeric = model.predict(input_vectorized)[0]

        # Map numeric prediction back to emotion name
        predicted_emotion = reverse_emotion_map.get(prediction_numeric, "Unknown")

        st.success(f"The predicted emotion is: **{predicted_emotion.capitalize()}**")
    else:
        st.warning("Please enter some text to predict.")